/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CrossPromo: typeof import('./src/components/CrossPromo.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    HelpFulLinks: typeof import('./src/components/HelpFulLinks.vue')['default']
    LicenseInfo: typeof import('./src/components/LicenseInfo.vue')['default']
    Metrics: typeof import('./src/components/Metrics.vue')['default']
    PendingVendors: typeof import('./src/components/PendingVendors.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopVendors: typeof import('./src/components/TopVendors.vue')['default']
  }
}
