/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminNoteCard: typeof import('./src/components/AIReview/AdminNoteCard.vue')['default']
    AIReviewDrawer: typeof import('./src/components/AIReview/AIReviewDrawer.vue')['default']
    AIReviewHeader: typeof import('./src/components/AIReview/AIReviewHeader.vue')['default']
    AuditResultsCard: typeof import('./src/components/AIReview/AuditResultsCard.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    ImageReviewsCard: typeof import('./src/components/AIReview/ImageReviewsCard.vue')['default']
    ProductsTable: typeof import('./src/components/ProductsTable.vue')['default']
    RequestChangeModal: typeof import('./src/components/RequestChangeModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilters: typeof import('./src/components/SearchFilters.vue')['default']
    StatusRiskRow: typeof import('./src/components/AIReview/StatusRiskRow.vue')['default']
    SuggestionsCard: typeof import('./src/components/AIReview/SuggestionsCard.vue')['default']
  }
}
